apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-wallet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-wallet
  template:
    metadata:
      labels:
        app: mock-wallet
    spec:
      containers:
        - name: wallet
          image: peeyushnaik/mock-wallet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
