apiVersion: v1
kind: Service
metadata:
  name: mock-wallet-service
spec:
  type: NodePort
  selector:
    app: mock-wallet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007